<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>" <?php echo $this->helper('lucky_microdata')->microdata('offers', ($_product->getTypeId() == 'grouped' ? 'AggregateOffer' : 'Offer') ); ?>>
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" <?php echo $this->helper('lucky_microdata')->microdata('image') ?>/></a>
            <?php // Product description ?>
            <div class="product-shop">
                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>" <?php echo $this->helper('lucky_microdata')->microdata('name'); ?>><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>

                <?php // Tier Price Microdata ?>
                <?php $_tierPrices = $this->helper('lucky_microdata')->getTierPrices($_product); ?>
                <?php if (!empty($_tierPrices)): ?>
                    <?php $j = 0; ?>
                    <?php foreach ($_tierPrices as $_price): ?>
                        <?php 
                            $_startTierPrice = $_tierPrices[$j++];
                            $_nextTierPrice = isset( $_tierPrices[$j] ) ? $_tierPrices[$i] : false;
                        ?>
                        <span <?php echo $this->helper('lucky_microdata')->microdata('priceSpecification', 'PriceSpecification'); ?>>
                            <?php echo $this->helper('lucky_microdata')->microdata('price', '', number_format( (float)$_startTierPrice['price'], 2 )); ?>
                            <span <?php echo $this->helper('lucky_microdata')->microdata('eligibleQuantity', 'QuantitativeValue'); ?>>
                                <?php 
                                    echo $this->helper('lucky_microdata')->microdata('minValue', '', $_startTierPrice['price_qty'] );
                                    if($_nextTierPrice) {
                                        echo $this->helper('lucky_microdata')->microdata('maxValue', '', $_nextTierPrice['price_qty'] - 1 ); 
                                    }
                                ?>
                            </span>
                        </span>
                    <?php endforeach; ?>
                <?php endif ?>

                <?php if($_product->isSaleable()): ?>
                    <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php echo $this->helper('lucky_microdata')->microdata('availability', '', 'InStock', 'link'); ?>
                <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php echo $this->helper('lucky_microdata')->microdata('availability', '', 'OutOfStock', 'link'); ?>
                <?php endif; ?>
                <div class="desc std">
                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                </div>
                <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" <?php echo $this->helper('lucky_microdata')->microdata('offers', ($_product->getTypeId() == 'grouped' ? 'AggregateOffer' : 'Offer') ); ?>>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" <?php echo $this->helper('lucky_microdata')->microdata('image') ?>/></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" <?php echo $this->helper('lucky_microdata')->microdata('name'); ?>><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>

                <?php // Tier Price Microdata ?>
                <?php $_tierPrices = $this->helper('lucky_microdata')->getTierPrices($_product); ?>
                <?php if (!empty($_tierPrices)): ?>
                    <?php $j = 0; ?>
                    <?php foreach ($_tierPrices as $_price): ?>
                        <?php 
                            $_startTierPrice = $_tierPrices[$j++];
                            $_nextTierPrice = isset( $_tierPrices[$j] ) ? $_tierPrices[$j] : false;
                        ?>
                        <span <?php echo $this->helper('lucky_microdata')->microdata('priceSpecification', 'PriceSpecification'); ?>>
                            <?php echo $this->helper('lucky_microdata')->microdata('price', '', number_format( (float)$_startTierPrice['price'], 2 )); ?>
                            <span <?php echo $this->helper('lucky_microdata')->microdata('eligibleQuantity', 'QuantitativeValue'); ?>>
                                <?php 
                                    echo $this->helper('lucky_microdata')->microdata('minValue', '', $_startTierPrice['price_qty'] );
                                    if($_nextTierPrice) {
                                        echo $this->helper('lucky_microdata')->microdata('maxValue', '', $_nextTierPrice['price_qty'] - 1 ); 
                                    }
                                ?>
                            </span>
                        </span>
                    <?php endforeach; ?>
                <?php endif ?>

                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php echo $this->helper('lucky_microdata')->microdata('availability', '', 'InStock', 'link'); ?>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php echo $this->helper('lucky_microdata')->microdata('availability', '', 'OutOfStock', 'link'); ?>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
